import { ComfyTheme } from "./types";

export const DEFAULT_THEME: ComfyTheme = {
  "id": "dark",
  "name": "Dark (Default)",
  "colors": {
    "node_slot": {
      "CLIP": "#FFD500",
      "CLIP_VISION": "#A8DADC",
      "CLIP_VISION_OUTPUT": "#ad7452",
      "CONDITIONING": "#FFA931",
      "CONTROL_NET": "#6EE7B7",
      "IMAGE": "#64B5F6",
      "LATENT": "#FF9CF9",
      "MASK": "#81C784",
      "MODEL": "#B39DDB",
      "STYLE_MODEL": "#C2FFAE",
      "VAE": "#FF6E6E",
      "NOISE": "#B0B0B0",
      "GUIDER": "#66FFFF",
      "SAMPLER": "#ECB4B4",
      "SIGMAS": "#CDFFCD",
      "TAESD": "#DCC274"
    },
    "litegraph_base": {
      "BACKGROUND_IMAGE": "",
      "CLEAR_BACKGROUND_COLOR": "#222222",
      "NODE_TITLE_COLOR": "#999999",
      "NODE_SELECTED_TITLE_COLOR": "#FFFFFF",
      "NODE_TEXT_SIZE": 14,
      "NODE_TEXT_COLOR": "#AAAAAA",
      "NODE_TEXT_HIGHLIGHT_COLOR": "#FFFFFF",
      "NODE_SUBTEXT_SIZE": 12,
      "NODE_DEFAULT_COLOR": "#333333",
      "NODE_DEFAULT_BGCOLOR": "#353535",
      "NODE_DEFAULT_BOXCOLOR": "#666666",
      "NODE_DEFAULT_SHAPE": 2,
      "NODE_BOX_OUTLINE_COLOR": "#FFFFFF",
      "NODE_BYPASS_BGCOLOR": "#FF00FF",
      "NODE_ERROR_COLOUR": "#EE0000",
      "DEFAULT_SHADOW_COLOR": "rgba(0,0,0,0.5)",
      "DEFAULT_GROUP_FONT": 24,
      "WIDGET_BGCOLOR": "#222222",
      "WIDGET_OUTLINE_COLOR": "#666666",
      "WIDGET_TEXT_COLOR": "#DDDDDD",
      "WIDGET_SECONDARY_TEXT_COLOR": "#999999",
      "WIDGET_DISABLED_TEXT_COLOR": "#666666",
      "LINK_COLOR": "#99AA99",
      "EVENT_LINK_COLOR": "#AA8866",
      "CONNECTING_LINK_COLOR": "#AAFFAA",
      "BADGE_FG_COLOR": "#FFFFFF",
      "BADGE_BG_COLOR": "#0F1F0F"
    },
    "comfy_base": {
      "fg-color": "#ffffff",
      "bg-color": "#202020",
      "comfy-menu-bg": "#353535",
      "comfy-menu-secondary-bg": "#303030",
      "comfy-input-bg": "#222222",
      "input-text": "#dddddd",
      "descrip-text": "#999999",
      "drag-text": "#cccccc",
      "error-text": "#ff4444",
      "border-color": "#4e4e4e",
      "tr-even-bg-color": "#222222",
      "tr-odd-bg-color": "#353535",
      "content-bg": "#4e4e4e",
      "content-fg": "#ffffff",
      "content-hover-bg": "#222222",
      "content-hover-fg": "#ffffff",
      "bar-shadow": "rgba(16, 16, 16, 0.5) 0 0 0.5rem"
    }
  }
};

export const PRESETS: ComfyTheme[] = [
  DEFAULT_THEME,
  {
    "id": "matrix",
    "name": "The Matrix",
    "colors": {
      "node_slot": {
        "CLIP": "#00FF41",
        "CLIP_VISION": "#008F11",
        "CLIP_VISION_OUTPUT": "#0D0208",
        "CONDITIONING": "#003B00",
        "CONTROL_NET": "#00FF41",
        "IMAGE": "#D1FFD1",
        "LATENT": "#00FF00",
        "MASK": "#008F11",
        "MODEL": "#00FF41",
        "STYLE_MODEL": "#008F11",
        "VAE": "#D1FFD1",
        "NOISE": "#303030",
        "GUIDER": "#00FF41",
        "SAMPLER": "#008F11",
        "SIGMAS": "#003B00",
        "TAESD": "#D1FFD1"
      },
      "litegraph_base": {
        "BACKGROUND_IMAGE": "",
        "CLEAR_BACKGROUND_COLOR": "#000000",
        "NODE_TITLE_COLOR": "#00FF41",
        "NODE_SELECTED_TITLE_COLOR": "#FFFFFF",
        "NODE_TEXT_SIZE": 14,
        "NODE_TEXT_COLOR": "#008F11",
        "NODE_TEXT_HIGHLIGHT_COLOR": "#00FF41",
        "NODE_SUBTEXT_SIZE": 12,
        "NODE_DEFAULT_COLOR": "#051005",
        "NODE_DEFAULT_BGCOLOR": "#020A02",
        "NODE_DEFAULT_BOXCOLOR": "#003B00",
        "NODE_DEFAULT_SHAPE": 2,
        "NODE_BOX_OUTLINE_COLOR": "#00FF41",
        "NODE_BYPASS_BGCOLOR": "#FF0000",
        "NODE_ERROR_COLOUR": "#FF0000",
        "DEFAULT_SHADOW_COLOR": "rgba(0, 255, 65, 0.2)",
        "DEFAULT_GROUP_FONT": 24,
        "WIDGET_BGCOLOR": "#000000",
        "WIDGET_OUTLINE_COLOR": "#003B00",
        "WIDGET_TEXT_COLOR": "#00FF41",
        "WIDGET_SECONDARY_TEXT_COLOR": "#008F11",
        "WIDGET_DISABLED_TEXT_COLOR": "#003B00",
        "LINK_COLOR": "#008F11",
        "EVENT_LINK_COLOR": "#00FF41",
        "CONNECTING_LINK_COLOR": "#D1FFD1",
        "BADGE_FG_COLOR": "#000000",
        "BADGE_BG_COLOR": "#00FF41"
      },
      "comfy_base": {
        "fg-color": "#00FF41",
        "bg-color": "#000000",
        "comfy-menu-bg": "#020A02",
        "comfy-menu-secondary-bg": "#051005",
        "comfy-input-bg": "#000000",
        "input-text": "#00FF41",
        "descrip-text": "#008F11",
        "drag-text": "#003B00",
        "error-text": "#FF0000",
        "border-color": "#003B00",
        "tr-even-bg-color": "#020A02",
        "tr-odd-bg-color": "#051005",
        "content-bg": "#003B00",
        "content-fg": "#00FF41",
        "content-hover-bg": "#008F11",
        "content-hover-fg": "#000000",
        "bar-shadow": "0 0 10px rgba(0, 255, 65, 0.3)"
      }
    }
  },
  {
    "id": "lotr",
    "name": "The One Ring",
    "colors": {
      "node_slot": {
        "CLIP": "#FFD700",
        "CLIP_VISION": "#2F4F4F",
        "CLIP_VISION_OUTPUT": "#8B4513",
        "CONDITIONING": "#556B2F",
        "CONTROL_NET": "#DAA520",
        "IMAGE": "#8FBC8F",
        "LATENT": "#483D8B",
        "MASK": "#2E8B57",
        "MODEL": "#CD853F",
        "STYLE_MODEL": "#DEB887",
        "VAE": "#BC8F8F",
        "NOISE": "#708090",
        "GUIDER": "#F0E68C",
        "SAMPLER": "#B8860B",
        "SIGMAS": "#556B2F",
        "TAESD": "#FFD700"
      },
      "litegraph_base": {
        "BACKGROUND_IMAGE": "",
        "CLEAR_BACKGROUND_COLOR": "#12100e",
        "NODE_TITLE_COLOR": "#FFC400",
        "NODE_SELECTED_TITLE_COLOR": "#FFFFFF",
        "NODE_TEXT_SIZE": 14,
        "NODE_TEXT_COLOR": "#D2B48C",
        "NODE_TEXT_HIGHLIGHT_COLOR": "#FFF8DC",
        "NODE_SUBTEXT_SIZE": 12,
        "NODE_DEFAULT_COLOR": "#2A2520",
        "NODE_DEFAULT_BGCOLOR": "#1F1C18",
        "NODE_DEFAULT_BOXCOLOR": "#3E3529",
        "NODE_DEFAULT_SHAPE": 2,
        "NODE_BOX_OUTLINE_COLOR": "#8B4513",
        "NODE_BYPASS_BGCOLOR": "#550000",
        "NODE_ERROR_COLOUR": "#8B0000",
        "DEFAULT_SHADOW_COLOR": "rgba(0,0,0,0.8)",
        "DEFAULT_GROUP_FONT": 24,
        "WIDGET_BGCOLOR": "#0F0E0C",
        "WIDGET_OUTLINE_COLOR": "#5C4033",
        "WIDGET_TEXT_COLOR": "#F4C430",
        "WIDGET_SECONDARY_TEXT_COLOR": "#A0522D",
        "WIDGET_DISABLED_TEXT_COLOR": "#4A4036",
        "LINK_COLOR": "#6B8E23",
        "EVENT_LINK_COLOR": "#FFD700",
        "CONNECTING_LINK_COLOR": "#F5F5DC",
        "BADGE_FG_COLOR": "#12100e",
        "BADGE_BG_COLOR": "#FFC400"
      },
      "comfy_base": {
        "fg-color": "#E6D0A0",
        "bg-color": "#12100e",
        "comfy-menu-bg": "#1C1916",
        "comfy-menu-secondary-bg": "#171512",
        "comfy-input-bg": "#0D0C0A",
        "input-text": "#D2B48C",
        "descrip-text": "#8B4513",
        "drag-text": "#A0522D",
        "error-text": "#8B0000",
        "border-color": "#3E3529",
        "tr-even-bg-color": "#1C1916",
        "tr-odd-bg-color": "#24201C",
        "content-bg": "#2A2520",
        "content-fg": "#F4C430",
        "content-hover-bg": "#3E3529",
        "content-hover-fg": "#FFFFFF",
        "bar-shadow": "0 0 15px rgba(0, 0, 0, 0.8)"
      }
    }
  },
  {
    "id": "starwars",
    "name": "Galactic Empire",
    "colors": {
      "node_slot": {
        "CLIP": "#FFE81F",
        "CLIP_VISION": "#FF0000",
        "CLIP_VISION_OUTPUT": "#FFFFFF",
        "CONDITIONING": "#FF0000",
        "CONTROL_NET": "#000000",
        "IMAGE": "#0066FF",
        "LATENT": "#FF3333",
        "MASK": "#CCCCCC",
        "MODEL": "#999999",
        "STYLE_MODEL": "#FFE81F",
        "VAE": "#FF0000",
        "NOISE": "#444444",
        "GUIDER": "#FFFFFF",
        "SAMPLER": "#FF0000",
        "SIGMAS": "#999999",
        "TAESD": "#FFE81F"
      },
      "litegraph_base": {
        "BACKGROUND_IMAGE": "",
        "CLEAR_BACKGROUND_COLOR": "#050505",
        "NODE_TITLE_COLOR": "#FF0000",
        "NODE_SELECTED_TITLE_COLOR": "#FFFFFF",
        "NODE_TEXT_SIZE": 14,
        "NODE_TEXT_COLOR": "#CCCCCC",
        "NODE_TEXT_HIGHLIGHT_COLOR": "#FFFFFF",
        "NODE_SUBTEXT_SIZE": 12,
        "NODE_DEFAULT_COLOR": "#111111",
        "NODE_DEFAULT_BGCOLOR": "#0A0A0A",
        "NODE_DEFAULT_BOXCOLOR": "#333333",
        "NODE_DEFAULT_SHAPE": 1,
        "NODE_BOX_OUTLINE_COLOR": "#444444",
        "NODE_BYPASS_BGCOLOR": "#330000",
        "NODE_ERROR_COLOUR": "#FF0000",
        "DEFAULT_SHADOW_COLOR": "rgba(255, 0, 0, 0.2)",
        "DEFAULT_GROUP_FONT": 24,
        "WIDGET_BGCOLOR": "#000000",
        "WIDGET_OUTLINE_COLOR": "#FF0000",
        "WIDGET_TEXT_COLOR": "#FFFFFF",
        "WIDGET_SECONDARY_TEXT_COLOR": "#FF3333",
        "WIDGET_DISABLED_TEXT_COLOR": "#333333",
        "LINK_COLOR": "#FF0000",
        "EVENT_LINK_COLOR": "#0066FF",
        "CONNECTING_LINK_COLOR": "#FFFFFF",
        "BADGE_FG_COLOR": "#FFFFFF",
        "BADGE_BG_COLOR": "#FF0000"
      },
      "comfy_base": {
        "fg-color": "#FFFFFF",
        "bg-color": "#050505",
        "comfy-menu-bg": "#111111",
        "comfy-menu-secondary-bg": "#0A0A0A",
        "comfy-input-bg": "#000000",
        "input-text": "#FF0000",
        "descrip-text": "#666666",
        "drag-text": "#FFFFFF",
        "error-text": "#FF0000",
        "border-color": "#333333",
        "tr-even-bg-color": "#0A0A0A",
        "tr-odd-bg-color": "#111111",
        "content-bg": "#333333",
        "content-fg": "#FFFFFF",
        "content-hover-bg": "#FF0000",
        "content-hover-fg": "#FFFFFF",
        "bar-shadow": "0 0 10px rgba(255, 0, 0, 0.3)"
      }
    }
  },
  {
    "id": "dune",
    "name": "Arrakis",
    "colors": {
      "node_slot": {
        "CLIP": "#F4A460",
        "CLIP_VISION": "#40E0D0",
        "CLIP_VISION_OUTPUT": "#8B4513",
        "CONDITIONING": "#1E90FF",
        "CONTROL_NET": "#DEB887",
        "IMAGE": "#00BFFF",
        "LATENT": "#FF8C00",
        "MASK": "#D2691E",
        "MODEL": "#F4A460",
        "STYLE_MODEL": "#B8860B",
        "VAE": "#4682B4",
        "NOISE": "#A0522D",
        "GUIDER": "#1E90FF",
        "SAMPLER": "#D2691E",
        "SIGMAS": "#40E0D0",
        "TAESD": "#F4A460"
      },
      "litegraph_base": {
        "BACKGROUND_IMAGE": "",
        "CLEAR_BACKGROUND_COLOR": "#191512",
        "NODE_TITLE_COLOR": "#1E90FF",
        "NODE_SELECTED_TITLE_COLOR": "#40E0D0",
        "NODE_TEXT_SIZE": 14,
        "NODE_TEXT_COLOR": "#D2B48C",
        "NODE_TEXT_HIGHLIGHT_COLOR": "#FFFFFF",
        "NODE_SUBTEXT_SIZE": 12,
        "NODE_DEFAULT_COLOR": "#2B221B",
        "NODE_DEFAULT_BGCOLOR": "#231C16",
        "NODE_DEFAULT_BOXCOLOR": "#A0522D",
        "NODE_DEFAULT_SHAPE": 2,
        "NODE_BOX_OUTLINE_COLOR": "#F4A460",
        "NODE_BYPASS_BGCOLOR": "#553322",
        "NODE_ERROR_COLOUR": "#8B0000",
        "DEFAULT_SHADOW_COLOR": "rgba(30, 144, 255, 0.2)",
        "DEFAULT_GROUP_FONT": 24,
        "WIDGET_BGCOLOR": "#14100E",
        "WIDGET_OUTLINE_COLOR": "#8B4513",
        "WIDGET_TEXT_COLOR": "#40E0D0",
        "WIDGET_SECONDARY_TEXT_COLOR": "#F4A460",
        "WIDGET_DISABLED_TEXT_COLOR": "#5C4033",
        "LINK_COLOR": "#1E90FF",
        "EVENT_LINK_COLOR": "#F4A460",
        "CONNECTING_LINK_COLOR": "#FFFFFF",
        "BADGE_FG_COLOR": "#191512",
        "BADGE_BG_COLOR": "#1E90FF"
      },
      "comfy_base": {
        "fg-color": "#E0C0A0",
        "bg-color": "#191512",
        "comfy-menu-bg": "#2B221B",
        "comfy-menu-secondary-bg": "#231C16",
        "comfy-input-bg": "#14100E",
        "input-text": "#40E0D0",
        "descrip-text": "#8B4513",
        "drag-text": "#F4A460",
        "error-text": "#FF4500",
        "border-color": "#5C4033",
        "tr-even-bg-color": "#231C16",
        "tr-odd-bg-color": "#2B221B",
        "content-bg": "#8B4513",
        "content-fg": "#FFFFFF",
        "content-hover-bg": "#1E90FF",
        "content-hover-fg": "#FFFFFF",
        "bar-shadow": "0 0 15px rgba(30, 144, 255, 0.2)"
      }
    }
  },
  {
    "id": "bttf",
    "name": "Back to the Future",
    "colors": {
      "node_slot": {
        "CLIP": "#FFB800", 
        "CLIP_VISION": "#FF0000", 
        "CLIP_VISION_OUTPUT": "#FF8800",
        "CONDITIONING": "#00FFFF", 
        "CONTROL_NET": "#C0C0C0",
        "IMAGE": "#FFB800",
        "LATENT": "#FF00FF",
        "MASK": "#00FF00",
        "MODEL": "#C0C0C0", 
        "STYLE_MODEL": "#FF4400",
        "VAE": "#00FFFF",
        "NOISE": "#888888",
        "GUIDER": "#FFB800",
        "SAMPLER": "#FF0000",
        "SIGMAS": "#00FF00",
        "TAESD": "#FFFF00"
      },
      "litegraph_base": {
        "BACKGROUND_IMAGE": "",
        "CLEAR_BACKGROUND_COLOR": "#1a1a24",
        "NODE_TITLE_COLOR": "#FFB800",
        "NODE_SELECTED_TITLE_COLOR": "#00FFFF",
        "NODE_TEXT_SIZE": 14,
        "NODE_TEXT_COLOR": "#e0e0e0",
        "NODE_TEXT_HIGHLIGHT_COLOR": "#FFFFFF",
        "NODE_SUBTEXT_SIZE": 12,
        "NODE_DEFAULT_COLOR": "#2d2d3a",
        "NODE_DEFAULT_BGCOLOR": "#22222e",
        "NODE_DEFAULT_BOXCOLOR": "#FF4400",
        "NODE_DEFAULT_SHAPE": 2,
        "NODE_BOX_OUTLINE_COLOR": "#FFB800",
        "NODE_BYPASS_BGCOLOR": "#FF00FF",
        "NODE_ERROR_COLOUR": "#FF0000",
        "DEFAULT_SHADOW_COLOR": "rgba(255, 184, 0, 0.2)",
        "DEFAULT_GROUP_FONT": 24,
        "WIDGET_BGCOLOR": "#101015",
        "WIDGET_OUTLINE_COLOR": "#FF8800",
        "WIDGET_TEXT_COLOR": "#00FFFF",
        "WIDGET_SECONDARY_TEXT_COLOR": "#FFB800",
        "WIDGET_DISABLED_TEXT_COLOR": "#666",
        "LINK_COLOR": "#00FFFF",
        "EVENT_LINK_COLOR": "#FFB800",
        "CONNECTING_LINK_COLOR": "#FFFFFF",
        "BADGE_FG_COLOR": "#000000",
        "BADGE_BG_COLOR": "#FFB800"
      },
      "comfy_base": {
        "fg-color": "#e0e0e0",
        "bg-color": "#1a1a24",
        "comfy-menu-bg": "#2d2d3a",
        "comfy-menu-secondary-bg": "#22222e",
        "comfy-input-bg": "#101015",
        "input-text": "#FFB800",
        "descrip-text": "#00FFFF",
        "drag-text": "#FF4400",
        "error-text": "#FF0000",
        "border-color": "#FF8800",
        "tr-even-bg-color": "#2d2d3a",
        "tr-odd-bg-color": "#22222e",
        "content-bg": "#FF8800",
        "content-fg": "#000000",
        "content-hover-bg": "#FFB800",
        "content-hover-fg": "#000000",
        "bar-shadow": "0 0 15px rgba(255, 136, 0, 0.3)"
      }
    }
  },
  {
    "id": "vaporwave",
    "name": "Vaporwave",
    "colors": {
      "node_slot": {
        "CLIP": "#FF71CE",
        "CLIP_VISION": "#01CDFE",
        "CLIP_VISION_OUTPUT": "#05FFA1",
        "CONDITIONING": "#B967FF",
        "CONTROL_NET": "#FFFB96",
        "IMAGE": "#01CDFE",
        "LATENT": "#FF71CE",
        "MASK": "#B967FF",
        "MODEL": "#FFFB96",
        "STYLE_MODEL": "#05FFA1",
        "VAE": "#FF71CE",
        "NOISE": "#01CDFE",
        "GUIDER": "#B967FF",
        "SAMPLER": "#05FFA1",
        "SIGMAS": "#FFFB96",
        "TAESD": "#FF71CE"
      },
      "litegraph_base": {
        "BACKGROUND_IMAGE": "",
        "CLEAR_BACKGROUND_COLOR": "#2B1A3F",
        "NODE_TITLE_COLOR": "#05FFA1",
        "NODE_SELECTED_TITLE_COLOR": "#FFFB96",
        "NODE_TEXT_SIZE": 14,
        "NODE_TEXT_COLOR": "#E0E0E0",
        "NODE_TEXT_HIGHLIGHT_COLOR": "#FFFFFF",
        "NODE_SUBTEXT_SIZE": 12,
        "NODE_DEFAULT_COLOR": "#4A2B69",
        "NODE_DEFAULT_BGCOLOR": "#362052",
        "NODE_DEFAULT_BOXCOLOR": "#B967FF",
        "NODE_DEFAULT_SHAPE": 2,
        "NODE_BOX_OUTLINE_COLOR": "#FF71CE",
        "NODE_BYPASS_BGCOLOR": "#FF00FF",
        "NODE_ERROR_COLOUR": "#FF0000",
        "DEFAULT_SHADOW_COLOR": "rgba(255, 113, 206, 0.4)",
        "DEFAULT_GROUP_FONT": 24,
        "WIDGET_BGCOLOR": "#2B1A3F",
        "WIDGET_OUTLINE_COLOR": "#01CDFE",
        "WIDGET_TEXT_COLOR": "#05FFA1",
        "WIDGET_SECONDARY_TEXT_COLOR": "#B967FF",
        "WIDGET_DISABLED_TEXT_COLOR": "#666",
        "LINK_COLOR": "#01CDFE",
        "EVENT_LINK_COLOR": "#FF71CE",
        "CONNECTING_LINK_COLOR": "#FFFB96",
        "BADGE_FG_COLOR": "#2B1A3F",
        "BADGE_BG_COLOR": "#05FFA1"
      },
      "comfy_base": {
        "fg-color": "#ffffff",
        "bg-color": "#2B1A3F",
        "comfy-menu-bg": "#4A2B69",
        "comfy-menu-secondary-bg": "#362052",
        "comfy-input-bg": "#201330",
        "input-text": "#FF71CE",
        "descrip-text": "#01CDFE",
        "drag-text": "#B967FF",
        "error-text": "#FF0000",
        "border-color": "#B967FF",
        "tr-even-bg-color": "#362052",
        "tr-odd-bg-color": "#4A2B69",
        "content-bg": "#01CDFE",
        "content-fg": "#2B1A3F",
        "content-hover-bg": "#05FFA1",
        "content-hover-fg": "#2B1A3F",
        "bar-shadow": "0 0 15px rgba(185, 103, 255, 0.5)"
      }
    }
  }
];